spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/job_spring_batch?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
        password: root
        username: root
    flyway:
        baseline-on-migrate: true
        enabled: false
        locations: classpath:db/migration
        schemas: job_spring_batch
    batch:
        initialize-schema: always